version: "3.9"

services:
  nextapp:
    container_name: sch-iot-ml-miniproject
    image: sch-iot-ml-miniproject
    build:
      context: .
      dockerfile: Dockerfile
      platform: linux/amd64
    ports:
      - "2022:3000"
    environment:
      - NODE_ENV=production
      - UPLOAD_ROOT=/app/uploads/evaluation-scores
    volumes:
      - /home/iot/iot-ml-miniproject/db:/app/db
      - /home/iot/iot-ml-miniproject/upload:/app/uploads/evaluation-scores
    restart: unless-stopped
